# Generated by Django 4.1 on 2022-11-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenging', '0002_message_delivered_message_is_seen_thread_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_msg',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_msg_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
