# Generated by Django 4.1 on 2022-11-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenging', '0003_thread_last_msg_thread_last_msg_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='last_msg_data',
            new_name='last_msg_date',
        ),
    ]
