# Generated by Django 4.1 on 2022-10-29 00:39

from django.db import migrations, models
import utilities.media_paths


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='avatar',
            field=models.ImageField(default='profiles/avatar_default.png', upload_to=utilities.media_paths.avatar_path),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
