# Generated by Django 4.1.3 on 2022-12-02 15:11

from django.db import migrations, models
import utilities.media_paths


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='defaults/photo.png', null=True, upload_to=utilities.media_paths.post_thumbnail_path)),
                ('alt_text', models.CharField(default='post image', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('key', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('publish', models.CharField(default='Public', max_length=35)),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
                ('excerpt', models.TextField(blank=True, max_length=2000, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbnail', models.ImageField(blank=True, default='posts/default-thumbnail.png', null=True, upload_to=utilities.media_paths.post_thumbnail_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_rate', models.BigIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ('-updated_at', 'activity_rate', '-created_at'),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=utilities.media_paths.post_video_path)),
                ('title', models.TextField(blank=True, max_length=150, null=True)),
                ('alt_text', models.CharField(default='post video', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, default='defaults/video.png', null=True, upload_to=utilities.media_paths.post_thumbnail_path)),
            ],
        ),
    ]
