# Generated by Django 4.1 on 2022-09-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
