# Generated by Django 4.1.3 on 2022-11-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_activity_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created_at'},
        ),
    ]
