# Generated by Django 4.1.3 on 2022-11-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created_at', 'ordering': ('-updated_at', 'activity_rate', '-created_at')},
        ),
    ]
