# Generated by Django 4.1.3 on 2022-11-04 18:36

from django.db import migrations, models
import utilities.media_paths


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utilities.media_paths.comment_file_path),
        ),
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=utilities.media_paths.comment_picture_path),
        ),
    ]
