# Generated by Django 4.1 on 2022-09-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='hint',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
