# Generated by Django 4.1.3 on 2022-11-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_content_notification_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='hint_img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
