# Generated by Django 4.0.6 on 2022-07-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0003_rename_id_supporter_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supporter',
            old_name='key',
            new_name='id',
        ),
    ]
