# Generated by Django 4.1.3 on 2022-11-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_2',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_3',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_privacy',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
