# Generated by Django 4.1.3 on 2022-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_2_user_email_3_user_email_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
    ]
