# Generated by Django 4.1.3 on 2022-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='posts',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
    ]
