# Generated by Django 4.1.3 on 2022-11-10 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feed', '0003_remove_feed_content_type_remove_feed_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='feed_objects',
        ),
        migrations.AddField(
            model_name='feed',
            name='content_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='object_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FeedObjects',
        ),
    ]
