# Generated by Django 4.1.3 on 2022-11-10 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feed', '0004_remove_feed_feed_objects_feed_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='object_id',
        ),
        migrations.CreateModel(
            name='FeedObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_objects',
            field=models.ManyToManyField(to='feed.feedobjects'),
        ),
    ]
