# Generated by Django 4.1.3 on 2022-11-10 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_feed_content_type_remove_feed_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedobjects',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
