# Generated by Django 4.1.3 on 2022-11-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_feedobjects_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_objects',
            field=models.ManyToManyField(blank=True, to='feed.feedobjects'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
