# Generated by Django 4.1.3 on 2022-11-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_feed_feed_objects_alter_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedobjects',
            name='id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
