# Generated by Django 4.1.3 on 2022-11-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_feedobjects_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedobjects',
            name='activity_rate',
            field=models.BigIntegerField(blank=True, default=1, null=True),
        ),
    ]
