# Generated by Django 4.1.3 on 2022-11-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_activity_rate'),
        ('feed', '0009_feedobjects_activity_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='feed_objects',
        ),
        migrations.RemoveField(
            model_name='feedobjects',
            name='activity_rate',
        ),
        migrations.AddField(
            model_name='feed',
            name='posts',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
    ]
