# Generated by Django 4.1.3 on 2022-11-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_remove_feed_feed_objects_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ('-created_at',)},
        ),
    ]
